version: '3'
services:
  api:
    build:
      dockerfile: src/Dockerfile
      context: .
    container_name: movies_auth
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: movies_db_auth
    restart: always
    volumes:
      - movies_auth_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7.4.1-alpine
    container_name: movies_redis_auth
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6380:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

volumes:
  movies_auth_data:
